on:
  release:
    types: [released]

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.7

      - name: Check latest RouterOS release
        id: routeros_latest_version
        run: echo 'routeros_latest_version='$(./bin/get-latest-routeros-version.sh) >> $GITHUB_OUTPUT

      - name: Found latest version
        run: echo "latest version is ${{ steps.routeros_latest_version.outputs.routeros_latest_version }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "mnazarenko/docker-routeros"
          flavor: |
            latest=false
          tags: |
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}
            type=pep440,pattern={{major}}
            type=raw,value=latest,enable=${{ steps.routeros_latest_version.outputs.routeros_latest_version == github.event.release.tag_name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            ROUTEROS_VERSION=${{ github.event.release.tag_name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
